In [1]:
####### Solution 2.2 starts here #######

In [2]:
import numpy as np

In [3]:
# 定义已知工程常数
E1 = 4.0; #Msi
E2 = 3.0; #Msi
E3 = 3.1; #Msi
v12 = 0.2;
v23 = 0.4;
v31 = 0.6;
G12 = 6.0; #Msi
G23 = 7.0; #Msi
G31 = 2.0; #Msi

In [4]:
# 根据工程常数计算柔度矩阵的系数
S11 = 1/E1;
S22 = 1/E2;
S33 = 1/E3;
S12 = -S11*v12;
S23 = -S22*v23;
S13 = -S33*v31;
S44 = 1/G23;
S55 = 1/G31;
S66 = 1/G12;

In [5]:
# 初始化柔度矩阵
S = np.zeros((6,6))
# 将柔度矩阵的非零元素依次赋值；注意Python的编码从0开始。
S[0,0] = S11;
S[1,1] = S22;
S[2,2] = S33;
S[3,3] = S44;
S[4,4] = S55;
S[5,5] = S66;
S[0,1] = S12;
S[1,0] = S[0,1];
S[0,2] = S13;
S[2,0] = S[0,2];
S[1,2] = S23;
S[2,1] = S[1,2];
# 打印柔度矩阵
print("柔度矩阵为： \n", S, "\n Unit: Msi-1")

柔度矩阵为： 
 [[ 0.25       -0.05       -0.19354839  0.          0.          0.        ]
 [-0.05        0.33333333 -0.13333333  0.          0.          0.        ]
 [-0.19354839 -0.13333333  0.32258065  0.          0.          0.        ]
 [ 0.          0.          0.          0.14285714  0.          0.        ]
 [ 0.          0.          0.          0.          0.5         0.        ]
 [ 0.          0.          0.          0.          0.          0.16666667]] 
 Unit: Msi-1


In [6]:
# 计算刚度矩阵，并打印
C = np.linalg.inv(S)
# 打印刚度矩阵
print("刚度矩阵为： \n", C, "\n Unit: Msi")

刚度矩阵为： 
 [[13.67462345  6.38950057 10.84576764  0.          0.          0.        ]
 [ 6.38950057  6.57975865  6.55333392  0.          0.          0.        ]
 [10.84576764  6.55333392 12.31617194  0.          0.          0.        ]
 [ 0.          0.          0.          7.          0.          0.        ]
 [ 0.          0.          0.          0.          2.          0.        ]
 [ 0.          0.          0.          0.          0.          6.        ]] 
 Unit: Msi


In [7]:
####### Solution 2.10 starts here #######

In [8]:
# 定义已知工程常数
E1 = 204.0; #GPa
E2 = 18.5; #GPa
v12 = 0.23;
G12 = 5.59; #GPa

In [9]:
# 根据工程常数计算柔度矩阵的系数
S11 = 1/E1;
S12 = -v12*S11;
S22 = 1/E2;
S66 = 1/G12;

In [10]:
# 初始化柔度矩阵
S = np.zeros((3,3))
# 将柔度矩阵的非零元素依次赋值；注意Python的编码从0开始。
S[0][0] = S11;
S[0][1] = S12;
S[1][0] = S[0][1];
S[1][1] = S22;
S[2][2] = S66;
# 打印柔度矩阵
print("柔度矩阵为： \n", S, "\n Unit: GPa-1")

柔度矩阵为： 
 [[ 0.00490196 -0.00112745  0.        ]
 [-0.00112745  0.05405405  0.        ]
 [ 0.          0.          0.17889088]] 
 Unit: GPa-1


In [11]:
# 矩阵运算求解折减刚度矩阵
Q = np.linalg.inv(S)
print("Reduced stiffness matrix =\n", Q, "\n Unit: GPa")

Reduced stiffness matrix =
 [[204.98336751   4.27551093   0.        ]
 [  4.27551093  18.58917794   0.        ]
 [  0.           0.           5.59      ]] 
 Unit: GPa


In [12]:
####### Solution 2.16 starts here #######

In [13]:
import math

In [14]:
# 计算转换矩阵 T
theta = 30/180*np.pi; # rad
c = np.cos(theta)
s = np.sin(theta)
T = np.array([[c**2, s**2, 2.0*c*s],
              [s**2, c**2, -2.0*c*s],
              [-s*c, s*c, c**2-s**2]])
# 打印转换矩阵 T
print("Transformation matrix =\n", T)

Transformation matrix =
 [[ 0.75       0.25       0.8660254]
 [ 0.25       0.75      -0.8660254]
 [-0.4330127  0.4330127  0.5      ]]


In [15]:
stress_xy = np.array([[4.0],[2.0],[-3.0]]); #MPa
print("stress_xy = \n",  stress_xy, 'MPa')
stress_12 = np.matmul(T, stress_xy)
print("stress_12 = \n", stress_12, 'MPa')
# 应力、应变在不同坐标系下的转换过程不涉及材料参数，因此与模量大小无关。

stress_xy = 
 [[ 4.]
 [ 2.]
 [-3.]] MPa
stress_12 = 
 [[ 0.90192379]
 [ 5.09807621]
 [-2.3660254 ]] MPa


In [16]:
####### Solution 2.17 starts here #######

In [17]:
# 定义R矩阵
R = np.array([[1, 0, 0],
              [0, 1, 0],
              [0, 0, 2]])
# 打印R矩阵
print(R)

[[1 0 0]
 [0 1 0]
 [0 0 2]]


In [18]:
strain_xy = np.array([[4.0],[2.0],[-3.0]])*1.0E-6
print("strain_xy = \n",  strain_xy)
strain_12 = np.linalg.multi_dot([R, T, np.linalg.inv(R), strain_xy])
print("strain_12 = \n", strain_12)

strain_xy = 
 [[ 4.e-06]
 [ 2.e-06]
 [-3.e-06]]
strain_12 = 
 [[ 2.20096189e-06]
 [ 3.79903811e-06]
 [-3.23205081e-06]]


In [19]:
####### Solution 2.22 starts here #######

In [20]:
# 定义已知工程常数
E1 = 29.59; #Msi
E2 = 2.683; #Msi
v12 = 0.23;
G12 = 0.811; #Msi
# 根据工程常数计算柔度矩阵的系数
S11 = 1/E1;
S12 = -v12*S11;
S22 = 1/E2;
S66 = 1/G12;
# 初始化柔度矩阵
S = np.zeros((3,3))
# 将柔度矩阵的非零元素依次赋值；注意Python的编码从0开始。
S[0][0] = S11;
S[0][1] = S12;
S[1][0] = S[0][1];
S[1][1] = S22;
S[2][2] = S66;
# 打印柔度矩阵
print("柔度矩阵为： \n", S, "\n Unit: GPa-1")

柔度矩阵为： 
 [[ 0.0337952  -0.0077729   0.        ]
 [-0.0077729   0.37271711  0.        ]
 [ 0.          0.          1.23304562]] 
 Unit: GPa-1


In [21]:
# 计算折减刚度矩阵Q
Q = np.linalg.inv(S)
# 计算转换矩阵 T
theta = 60/180*np.pi; # rad
c = np.cos(theta)
s = np.sin(theta)
T = np.array([[c**2, s**2, 2.0*c*s],
              [s**2, c**2, -2.0*c*s],
              [-s*c, s*c, c**2-s**2]])
# 计算全局坐标下的折减刚度矩阵Q_bar
Q_bar = np.linalg.multi_dot([np.linalg.inv(T), Q, R, T, np.linalg.inv(R)])
# 计算全局坐标系下的柔度矩阵S_bar
S_bar = np.linalg.inv(Q_bar)
Ex = 1./S_bar[0,0]
Ey = 1./S_bar[1,1]
Gxy = 1./S_bar[2,2]
vxy = -S_bar[0,1]/S_bar[0,0]
mx = -S_bar[0,2]*E1
my = -S_bar[1,2]*E1

print("Ex = ", Ex)
print("Ey = ", Ey)
print("Gxy = ", Gxy)
print("vxy = ", vxy)
print("mx = ", mx)
print("my = ", my)

Ex =  2.27248560773396
Ey =  3.695684916057524
Gxy =  1.6004994028232264
vxy =  0.3632183205592983
mx =  -0.8529749039925613
my =  9.538083193082345


In [22]:
####### Solution 2.35 starts here #######

In [23]:
# 定义单层板强度指标
sigma_1T = 1260.0; # MPa
sigma_1C = 2500.0; # MPa
sigma_2T = 61.0; # MPa
sigma_2C = 202.0; # MPa
tau_ABS = 67.0; # MPa

# 计算转换矩阵 T
import numpy as np
theta = 60/180*np.pi; # rad
c = np.cos(theta)
s = np.sin(theta)
T = np.array([[c**2, s**2, 2.0*c*s],
              [s**2, c**2, -2.0*c*s],
              [-s*c, s*c, c**2-s**2]])

from sympy import symbols, solve
tau_xy = symbols('tau_xy')

stress_xy = np.array([0, 0, tau_xy])
stress_12 = np.linalg.multi_dot([T, stress_xy])

sigma1 = stress_12[0]
sigma2 = stress_12[1]
tau12 = stress_12[2]

# 最大应力准则
solve([sigma1 > -sigma_1C, sigma1 < sigma_1T, 
       sigma2 > -sigma_2C, sigma2 < sigma_2T, 
       tau12 > - tau_ABS, tau12 < tau_ABS])

(-70.4367328411343 < tau_xy) & (tau_xy < 134.0)

In [24]:
# 最大应变准则，首先需要计算材料坐标系下的应变

####### Solution 2.10 starts here #######
# 定义已知工程常数
E1 = 204.0; #GPa
E2 = 18.5; #GPa
v12 = 0.23;
G12 = 5.59; #GPa
# 根据工程常数计算柔度矩阵的系数
S11 = 1/E1;
S12 = -v12*S11;
S22 = 1/E2;
S66 = 1/G12;
# 初始化柔度矩阵
S = np.zeros((3,3))
# 将柔度矩阵的非零元素依次赋值；注意Python的编码从0开始。
S[0][0] = S11;
S[0][1] = S12;
S[1][0] = S[0][1];
S[1][1] = S22;
S[2][2] = S66;

strain_12 = np.linalg.multi_dot([S, stress_12])

epsilon1 = strain_12[0]
epsilon2 = strain_12[1]
gamma12 = strain_12[2]

In [25]:
# 最大应变准则
solve([epsilon1 > -sigma_1C/E1, epsilon1 < sigma_1T/E1, 
       epsilon2 > -sigma_2C/E2, epsilon2 < sigma_2T/E2, 
       gamma12 > - tau_ABS/G12, gamma12 < tau_ABS/G12])

(-68.9975918925903 < tau_xy) & (tau_xy < 134.0)

In [26]:
# Tasi-Hill准则
solve((sigma1/sigma_1T)**2 - (sigma1*sigma2)/sigma_1T**2 + (sigma2/sigma_2T)**2 + (tau12/tau_ABS)**2 < 1.0)

(-62.2337383095744 < tau_xy) & (tau_xy < 62.2337383095744)

In [27]:
# Tasi-Wu准则
H1 = 1/sigma_1T - 1/sigma_1C
H11 = 1/(sigma_1T*sigma_1C)
H2 = 1/sigma_2T - 1/sigma_2C
H22 = 1/(sigma_2T*sigma_2C)
H6 = 0
H66 = 1/tau_ABS**2
H12 = -0.5*np.sqrt(1/(sigma_1T*sigma_1C*sigma_2T*sigma_2C))

solve(H1*sigma1 + H2*sigma2 + H11*sigma1**2 + H22*sigma2**2 + H66*tau12**2 + 2.0*H12*sigma1*sigma2 < 1.0)

(-59.6537255794834 < tau_xy) & (tau_xy < 138.99621243935)