In [1]:
# Solution 4.3
import numpy as np
# 已知条件：中性面应变和曲率
epsilon_0 = np.array([[2E-6], [3e-6], [4e-6]])
kappa_0 = np.array([[1.2e-4], [1.5e-4], [2.6e-4]])
# 层合板厚度为 0.015
# 计算层合板上表面的全局应变：
epsilon_top = epsilon_0 + (-0.0075)* kappa_0
print("层合板上表面的全局应变：\n", epsilon_top)
# 计算层合板中性面的全局应变：
epsilon_mid = epsilon_0 + (0.0)* kappa_0
print("层合板中性面的全局应变：\n", epsilon_mid)
# 计算层合板下表面的全局应变：
epsilon_bottom = epsilon_0 + (0.0075)* kappa_0
print("层合板下表面的全局应变：\n", epsilon_bottom)

层合板上表面的全局应变：
 [[1.100e-06]
 [1.875e-06]
 [2.050e-06]]
层合板中性面的全局应变：
 [[2.e-06]
 [3.e-06]
 [4.e-06]]
层合板下表面的全局应变：
 [[2.900e-06]
 [4.125e-06]
 [5.950e-06]]


In [2]:
# 定义函数由单层板的工程常数计算单层板折减刚度矩阵Q
def transform_engineeringConstants(E1, E2, v12, G12):
    # 根据工程常数计算柔度矩阵的系数
    S11 = 1/E1;
    S12 = -v12/E1;
    S22 = 1/E2;
    S66 = 1/G12;
    # 初始化柔度矩阵
    S = np.zeros((3,3))
    # 将柔度矩阵的非零元素依次赋值；注意Python的编码从0开始。
    S[0][0] = S11;
    S[0][1] = S12;
    S[1][0] = S[0][1];
    S[1][1] = S22;
    S[2][2] = S66;
    # 矩阵运算求解折减刚度矩阵
    Q = np.linalg.inv(S)
    return Q

In [3]:
# 定义函数由单层板折减刚度矩阵Q和铺层角度，计算单层板在全局坐标系下的折减刚度矩阵Q_bar
def transform_Q(Q, theta):
    # 计算转换矩阵 T
    c = np.cos(theta*np.pi/180.0)
    s = np.sin(theta*np.pi/180.0)
    T = np.zeros((3,3))
    T[0][0] = c**2;
    T[0][1] = s**2;
    T[0][2] = 2.0*c*s;
    T[1][0] = s**2;
    T[1][1] = c**2;
    T[1][2] = -2.0*c*s;
    T[2][0] = -s*c;
    T[2][1] = s*c;
    T[2][2] = c**2-s**2;
    # 定义R矩阵
    R = np.zeros((3,3))
    R[0][0] = 1;
    R[1][1] = 1;
    R[2][2] = 2;
    # 计算全局折减刚度矩阵
    Q_bar = np.linalg.multi_dot([np.linalg.inv(T), Q, R, T, np.linalg.inv(R)])
    return Q_bar

In [4]:
def height(thickness):
    # thickness = np.array([5, 5, 5])
    ply_num = len(thickness)
    h_total = np.sum(thickness[0:ply_num]) # 层合板总厚度
    height = np.zeros(ply_num+1)
    #Create array storing the heights of k plies about the midplane
    for k in range(0, ply_num+1):
        height[k]= - h_total/2.0 + np.sum(thickness[0:k])
    return height

In [5]:
def ABD_matrices(Q, statck, thickness):
    A = np.zeros([3, 3])
    B = np.zeros([3, 3])
    D = np.zeros([3, 3])
    h = height(thickness)
    for i in range(3):
        for j in range(3):
            for k in range(len(h)-1):
                Q_bar = transform_Q(Q, statck[k])
                ply_kA = h[k+1] - h[k]
                ply_kB = (h[k+1]**2 - h[k]**2)/2
                ply_kD = (h[k+1]**3 - h[k]**3)/3
                A[i,j] = A[i,j] + ply_kA * Q_bar[i,j]
                B[i,j] = B[i,j] + ply_kB * Q_bar[i,j]
                D[i,j] = D[i,j] + ply_kD * Q_bar[i,j]
    return (A, B, D)

In [6]:
# Solution 4.8
Q = transform_engineeringConstants(5.6*1.0E6, 1.2*1.0E6, 0.26, 0.6*1.0E6)
thickness = np.array([0.005, 0.005, 0.005])
statck = np.array([0, 60, -60])
# 注意 ABD_matrices 中包含A, B, D共三个矩阵，每个矩阵都是3X3的
A = ABD_matrices(Q, statck, thickness)[0]
B = ABD_matrices(Q, statck, thickness)[1]
D = ABD_matrices(Q, statck, thickness)[2]
print("A = ", A)
print("B = ", B)
print("D = ", D)

A =  [[4.44994202e+04 1.19989998e+04 4.54747351e-13]
 [1.19989998e+04 4.44994202e+04 1.81898940e-12]
 [4.54747351e-13 9.09494702e-13 1.62502102e+04]]
B =  [[-101.83816282   18.12552547  -13.70097984]
 [  18.12552547   65.58711188  -34.63053386]
 [ -13.70097984  -34.63053386   18.12552547]]
D =  [[ 1.0040944   0.19477204 -0.0685049 ]
 [ 0.19477204  0.72505228 -0.17315267]
 [-0.0685049  -0.17315267  0.27448223]]


In [7]:
# 层合板质量计算
# 层合板体积v_c
v_c = 5.*7.*0.015;
# 纤维密度rho_f，基体密度rho_m # 注意需要将kg/m3 转换为 lbm/in3
rho_f = 2.5*1000*3.6127e-5; rho_m = 1.2*1000*3.6127e-5;
# 查表格2.2得到纤维体积分数为0.45，计算层合板密度rho_c
rho_c = rho_f * 0.45 + rho_m * (1.0-0.45)
# 层合板质量m
m = rho_c * v_c
print("层合板质量为：", m)

层合板质量为： 0.033855514875000006


### Solution 4.9
$A  = \begin{bmatrix}
\frac{E}{1-v^2} & \frac{Ev}{1-v^2} & 0 \\
\frac{Ev}{1-v^2} & \frac{E}{1-v^2} & 0 \\
 0 & 0 & \frac{E}{2(1+v)}
\end{bmatrix}t$

$B = 0$

$D  = \frac{1}{12} \begin{bmatrix}
\frac{E}{1-v^2} & \frac{Ev}{1-v^2} & 0 \\
\frac{Ev}{1-v^2} & \frac{E}{1-v^2} & 0 \\
 0 & 0 & \frac{E}{2(1+v)}
\end{bmatrix}t^3$



In [8]:
# Solution 4.14
Q = transform_engineeringConstants(26.25*1.0E6, 1.49*1.0E6, 0.28, 1.04*1.0E6)
thickness = np.array([0.005, 0.005, 0.005])
statck = np.array([0, 60, -60])
# 注意 ABD_matrices 中包含A, B, D共三个矩阵，每个矩阵都是3X3的
A = ABD_matrices(Q, statck, thickness)[0]
B = ABD_matrices(Q, statck, thickness)[1]
D = ABD_matrices(Q, statck, thickness)[2]
print("A = ", A)
print("B = ", B)
print("D = ", D)

A =  [[1.66106485e+05 4.91594773e+04 3.63797881e-12]
 [4.91594773e+04 1.66106485e+05 7.27595761e-12]
 [1.81898940e-12 7.27595761e-12 5.84735038e+04]]
B =  [[-573.50896898  107.18375962  -72.73392011]
 [ 107.18375962  359.14144974 -196.49906505]
 [ -72.73392011 -196.49906505  107.18375962]]
D =  [[ 4.07034487  0.7431006  -0.3636696 ]
 [ 0.7431006   2.51592751 -0.98249533]
 [-0.3636696  -0.98249533  0.9177386 ]]


In [9]:
# 将3个3x3的A，B，D矩阵组装称为一个6x6的ABD矩阵
ABD_matrix = np.concatenate((np.concatenate((A, B), axis = 0), np.concatenate((B, D), axis = 0)), axis = 1)
print(ABD_matrix)

[[ 1.66106485e+05  4.91594773e+04  3.63797881e-12 -5.73508969e+02
   1.07183760e+02 -7.27339201e+01]
 [ 4.91594773e+04  1.66106485e+05  7.27595761e-12  1.07183760e+02
   3.59141450e+02 -1.96499065e+02]
 [ 1.81898940e-12  7.27595761e-12  5.84735038e+04 -7.27339201e+01
  -1.96499065e+02  1.07183760e+02]
 [-5.73508969e+02  1.07183760e+02 -7.27339201e+01  4.07034487e+00
   7.43100599e-01 -3.63669601e-01]
 [ 1.07183760e+02  3.59141450e+02 -1.96499065e+02  7.43100599e-01
   2.51592751e+00 -9.82495325e-01]
 [-7.27339201e+01 -1.96499065e+02  1.07183760e+02 -3.63669601e-01
  -9.82495325e-01  9.17738598e-01]]


In [10]:
# strain 表达中性面变形的向量：第1-3位为应变，第4-6位为曲率
# force 表达层合板承受的载荷：第1-3位为面内力，第4-6位为弯矩
strain = np.array([[0.0], [0.0], [0.0], [0.1], [0.1], [0.0]])
force = np.linalg.multi_dot([ABD_matrix, strain])
print("层合板受的载荷为：", force)

层合板受的载荷为： [[-46.63252094]
 [ 46.63252094]
 [-26.92329852]
 [  0.48134455]
 [  0.32590281]
 [ -0.13461649]]


In [11]:
# Solution 4.15
# 定义碳环氧单层板已知工程常数
E1 = 181.0*1.0E9; #Pa
E2 = 10.3*1.0E9; #Pa
v12 = 0.28;
G12 = 7.17*1.0E9; #Pa

In [12]:
Q = transform_engineeringConstants(E1, E2, v12, G12)
thickness = np.array([0.005, 0.005, 0.005, 0.005])
statck = np.array([45, -45, -45, 45])
# 注意 ABD_matrices 中包含A, B, D共三个矩阵，每个矩阵都是3X3的
A = ABD_matrices(Q, statck, thickness)[0]
B = ABD_matrices(Q, statck, thickness)[1]
D = ABD_matrices(Q, statck, thickness)[2]
print("A = ", A)
print("B = ", B)
print("D = ", D)

A =  [[1.13315573e+09 8.46355732e+08 8.94069672e-08]
 [8.46355732e+08 1.13315573e+09 5.96046448e-08]
 [8.94069672e-08 5.96046448e-08 9.31817243e+08]]
B =  [[-4.65661287e-10 -4.65661287e-10  4.65661287e-10]
 [-4.65661287e-10  0.00000000e+00  0.00000000e+00]
 [ 4.65661287e-10  0.00000000e+00 -2.32830644e-10]]
D =  [[37771.85774382 28211.85774382 21433.12251432]
 [28211.85774382 37771.85774382 21433.12251432]
 [21433.12251432 21433.12251432 31060.57478092]]


In [18]:
inv_A = np.linalg.inv(A)
Ex = 1./0.02/inv_A[0,0]
Ey = 1./0.02/inv_A[1,1]
Gxy = 1./0.02/inv_A[2,2]
print("Ex = ", Ex, 'Pa')
print("Ey = ", Ey, 'Pa')
print("Gxy = ", Gxy, 'Pa')

Ex =  25050567713.937263 Pa
Ey =  25050567713.937252 Pa
Gxy =  46590862171.38473 Pa


In [20]:
inv_D = np.linalg.inv(D)
Exf = 12./0.02**3/inv_D[0,0]
Eyf = 12./0.02**3/inv_D[1,1]
Gxyf = 12./0.02**3/inv_D[2,2]
print("Exf = ", Exf, 'Pa')
print("Eyf = ", Eyf, 'Pa')
print("Gxyf = ", Gxyf, 'Pa')

Exf =  22714902381.99696 Pa
Eyf =  22714902381.99695 Pa
Gxyf =  25704857011.517952 Pa
