In [1]:
import numpy as np

In [2]:
# 定义已知应力分量
sigma1 = 2.0*1.0E6; #Pa
sigma2 = -3.0*1.0E6; #Pa
tau12 = 4.0*1.0e6; #Pa

In [3]:
# 定义已知工程常数
E1 = 181.0*1.0E9; #Pa
E2 = 10.3*1.0E9; #Pa
v12 = 0.28;
G12 = 7.17*1.0E9; #Pa

In [4]:
# 根据工程常数计算柔度矩阵的系数
S11 = 1/E1;
S12 = -v12/E1;
S22 = 1/E2;
S66 = 1/G12;
# 打印计算结果
print("S11 =", S11, "Pa-1")
print("S12 =", S12, "Pa-1")
print("S22 =", S22, "Pa-1")
print("S66 =", S66, "Pa-1")

S11 = 5.524861878453039e-12 Pa-1
S12 = -1.546961325966851e-12 Pa-1
S22 = 9.70873786407767e-11 Pa-1
S66 = 1.394700139470014e-10 Pa-1


In [5]:
# 初始化柔度矩阵
S = np.zeros((3,3))
# 将柔度矩阵的非零元素依次赋值；注意Python的编码从0开始。
S[0][0] = S11;
S[0][1] = S12;
S[1][0] = S[0][1];
S[1][1] = S22;
S[2][2] = S66;
# 打印柔度矩阵
print("Compliance matrix = \n", S, "\n Unit: Pa-1")

Compliance matrix = 
 [[ 5.52486188e-12 -1.54696133e-12  0.00000000e+00]
 [-1.54696133e-12  9.70873786e-11  0.00000000e+00]
 [ 0.00000000e+00  0.00000000e+00  1.39470014e-10]] 
 Unit: Pa-1


In [6]:
# 计算次泊松比，并打印
v21 = v12/E1*E2;
print("v21 =",v21)

v21 = 0.015933701657458565


In [19]:
# 矩阵运算求解折减刚度矩阵
Q = np.linalg.inv(S)
print("Reduced stiffness matrix =\n", Q, "\n Unit: Pa")

Reduced stiffness matrix =
 [[1.81811139e+11 2.89692444e+09 0.00000000e+00]
 [2.89692444e+09 1.03461587e+10 0.00000000e+00]
 [0.00000000e+00 0.00000000e+00 7.17000000e+09]] 
 Unit: Pa


In [18]:
# 定义应力、应变矢量
stress = np.zeros((3,1))
strain = np.zeros((3,1))
# 给应力矢量赋值
stress[0] = sigma1;
stress[1] = sigma2;
stress[2] = tau12;
# 矩阵运算求解应变矢量
strain = np.matmul(S, stress);
# 打印计算结果
print("strain = \n", strain)

strain = 
 [[ 1.56906077e-05]
 [-2.94356059e-04]
 [ 5.57880056e-04]]
